# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lane_msgs/LaneList.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import lane_msgs.msg
import std_msgs.msg

class LaneList(genpy.Message):
  _md5sum = "7c734ba2a0461f54efa410edc16ce01f"
  _type = "lane_msgs/LaneList"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
Lane[] lane_list
int32 num_lanes
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: lane_msgs/Lane
LanePoint[] lane
int32 num_points
int32 attribute  # attribute: the left-left lane is 1, the left lane is 2, the right lane is 3, and the right-right lane is 4.
int32 track_id
int32 category

================================================================================
MSG: lane_msgs/LanePoint
float32 x
float32 y
float32 z
float32 visibility"""
  __slots__ = ['header','lane_list','num_lanes']
  _slot_types = ['std_msgs/Header','lane_msgs/Lane[]','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,lane_list,num_lanes

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LaneList, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lane_list is None:
        self.lane_list = []
      if self.num_lanes is None:
        self.num_lanes = 0
    else:
      self.header = std_msgs.msg.Header()
      self.lane_list = []
      self.num_lanes = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.lane_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.lane_list:
        length = len(val1.lane)
        buff.write(_struct_I.pack(length))
        for val2 in val1.lane:
          _x = val2
          buff.write(_get_struct_4f().pack(_x.x, _x.y, _x.z, _x.visibility))
        _x = val1
        buff.write(_get_struct_4i().pack(_x.num_points, _x.attribute, _x.track_id, _x.category))
      _x = self.num_lanes
      buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lane_list is None:
        self.lane_list = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.lane_list = []
      for i in range(0, length):
        val1 = lane_msgs.msg.Lane()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.lane = []
        for i in range(0, length):
          val2 = lane_msgs.msg.LanePoint()
          _x = val2
          start = end
          end += 16
          (_x.x, _x.y, _x.z, _x.visibility,) = _get_struct_4f().unpack(str[start:end])
          val1.lane.append(val2)
        _x = val1
        start = end
        end += 16
        (_x.num_points, _x.attribute, _x.track_id, _x.category,) = _get_struct_4i().unpack(str[start:end])
        self.lane_list.append(val1)
      start = end
      end += 4
      (self.num_lanes,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.lane_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.lane_list:
        length = len(val1.lane)
        buff.write(_struct_I.pack(length))
        for val2 in val1.lane:
          _x = val2
          buff.write(_get_struct_4f().pack(_x.x, _x.y, _x.z, _x.visibility))
        _x = val1
        buff.write(_get_struct_4i().pack(_x.num_points, _x.attribute, _x.track_id, _x.category))
      _x = self.num_lanes
      buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lane_list is None:
        self.lane_list = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.lane_list = []
      for i in range(0, length):
        val1 = lane_msgs.msg.Lane()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.lane = []
        for i in range(0, length):
          val2 = lane_msgs.msg.LanePoint()
          _x = val2
          start = end
          end += 16
          (_x.x, _x.y, _x.z, _x.visibility,) = _get_struct_4f().unpack(str[start:end])
          val1.lane.append(val2)
        _x = val1
        start = end
        end += 16
        (_x.num_points, _x.attribute, _x.track_id, _x.category,) = _get_struct_4i().unpack(str[start:end])
        self.lane_list.append(val1)
      start = end
      end += 4
      (self.num_lanes,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
_struct_4i = None
def _get_struct_4i():
    global _struct_4i
    if _struct_4i is None:
        _struct_4i = struct.Struct("<4i")
    return _struct_4i
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
