// Generated by gencpp from file openlane_bag/LanePoint.msg
// DO NOT EDIT!


#ifndef OPENLANE_BAG_MESSAGE_LANEPOINT_H
#define OPENLANE_BAG_MESSAGE_LANEPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openlane_bag
{
template <class ContainerAllocator>
struct LanePoint_
{
  typedef LanePoint_<ContainerAllocator> Type;

  LanePoint_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , visibility(0.0)  {
    }
  LanePoint_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , visibility(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _visibility_type;
  _visibility_type visibility;





  typedef boost::shared_ptr< ::openlane_bag::LanePoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openlane_bag::LanePoint_<ContainerAllocator> const> ConstPtr;

}; // struct LanePoint_

typedef ::openlane_bag::LanePoint_<std::allocator<void> > LanePoint;

typedef boost::shared_ptr< ::openlane_bag::LanePoint > LanePointPtr;
typedef boost::shared_ptr< ::openlane_bag::LanePoint const> LanePointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openlane_bag::LanePoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openlane_bag::LanePoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openlane_bag::LanePoint_<ContainerAllocator1> & lhs, const ::openlane_bag::LanePoint_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.visibility == rhs.visibility;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openlane_bag::LanePoint_<ContainerAllocator1> & lhs, const ::openlane_bag::LanePoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openlane_bag

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::openlane_bag::LanePoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openlane_bag::LanePoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openlane_bag::LanePoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openlane_bag::LanePoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openlane_bag::LanePoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openlane_bag::LanePoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openlane_bag::LanePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e3d90e07dd35cfd897ffc2308933bfc";
  }

  static const char* value(const ::openlane_bag::LanePoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e3d90e07dd35cfdULL;
  static const uint64_t static_value2 = 0x897ffc2308933bfcULL;
};

template<class ContainerAllocator>
struct DataType< ::openlane_bag::LanePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openlane_bag/LanePoint";
  }

  static const char* value(const ::openlane_bag::LanePoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openlane_bag::LanePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 visibility\n"
;
  }

  static const char* value(const ::openlane_bag::LanePoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openlane_bag::LanePoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.visibility);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LanePoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openlane_bag::LanePoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openlane_bag::LanePoint_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "visibility: ";
    Printer<float>::stream(s, indent + "  ", v.visibility);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENLANE_BAG_MESSAGE_LANEPOINT_H
