// Generated by gencpp from file openlane_bag/LaneList.msg
// DO NOT EDIT!


#ifndef OPENLANE_BAG_MESSAGE_LANELIST_H
#define OPENLANE_BAG_MESSAGE_LANELIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <openlane_bag/Lane.h>

namespace openlane_bag
{
template <class ContainerAllocator>
struct LaneList_
{
  typedef LaneList_<ContainerAllocator> Type;

  LaneList_()
    : header()
    , lane_list()
    , num_lanes(0)  {
    }
  LaneList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lane_list(_alloc)
    , num_lanes(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::openlane_bag::Lane_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::openlane_bag::Lane_<ContainerAllocator> >> _lane_list_type;
  _lane_list_type lane_list;

   typedef int32_t _num_lanes_type;
  _num_lanes_type num_lanes;





  typedef boost::shared_ptr< ::openlane_bag::LaneList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openlane_bag::LaneList_<ContainerAllocator> const> ConstPtr;

}; // struct LaneList_

typedef ::openlane_bag::LaneList_<std::allocator<void> > LaneList;

typedef boost::shared_ptr< ::openlane_bag::LaneList > LaneListPtr;
typedef boost::shared_ptr< ::openlane_bag::LaneList const> LaneListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openlane_bag::LaneList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openlane_bag::LaneList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openlane_bag::LaneList_<ContainerAllocator1> & lhs, const ::openlane_bag::LaneList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lane_list == rhs.lane_list &&
    lhs.num_lanes == rhs.num_lanes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openlane_bag::LaneList_<ContainerAllocator1> & lhs, const ::openlane_bag::LaneList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openlane_bag

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::openlane_bag::LaneList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openlane_bag::LaneList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openlane_bag::LaneList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openlane_bag::LaneList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openlane_bag::LaneList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openlane_bag::LaneList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openlane_bag::LaneList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c734ba2a0461f54efa410edc16ce01f";
  }

  static const char* value(const ::openlane_bag::LaneList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c734ba2a0461f54ULL;
  static const uint64_t static_value2 = 0xefa410edc16ce01fULL;
};

template<class ContainerAllocator>
struct DataType< ::openlane_bag::LaneList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openlane_bag/LaneList";
  }

  static const char* value(const ::openlane_bag::LaneList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openlane_bag::LaneList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Lane[] lane_list\n"
"int32 num_lanes\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: openlane_bag/Lane\n"
"LanePoint[] lane\n"
"int32 num_points\n"
"int32 attribute  # attribute: the left-left lane is 1, the left lane is 2, the right lane is 3, and the right-right lane is 4.\n"
"int32 track_id\n"
"int32 category\n"
"\n"
"================================================================================\n"
"MSG: openlane_bag/LanePoint\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 visibility\n"
;
  }

  static const char* value(const ::openlane_bag::LaneList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openlane_bag::LaneList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lane_list);
      stream.next(m.num_lanes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaneList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openlane_bag::LaneList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openlane_bag::LaneList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lane_list[]" << std::endl;
    for (size_t i = 0; i < v.lane_list.size(); ++i)
    {
      s << indent << "  lane_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::openlane_bag::Lane_<ContainerAllocator> >::stream(s, indent + "    ", v.lane_list[i]);
    }
    s << indent << "num_lanes: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_lanes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENLANE_BAG_MESSAGE_LANELIST_H
